name: Automatic PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automatic_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          yarn
      - name: Authenticate and Run GitHub Copilot
        run: |
          gh extension install github/gh-copilot
          export GITHUB_TOKEN=
          gh auth login --web -h github.com
          echo "COPILOT_ANALYSIS_RESULT=$(gh copilot explain "install git")" >> $GITHUB_ENV

      - name: Create review comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.BIBEK_GITHUB_TOKEN }}
          script: |
            try {
              const { data } = await github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: 'Here are the automatic review comments:\n' + process.env.COPILOT_ANALYSIS_RESULT,
                event: 'COMMENT'
              });
              console.log(data);
            } catch (error) {
              console.error('Failed to create review comment:', error);
            }
  
            
            